//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgAT110887
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountRRef { get; set; }
        public byte[] C_Fld10869RRef { get; set; }
        public byte[] C_Fld10870RRef { get; set; }
        public byte[] C_Fld11340RRef { get; set; }
        public byte[] C_Value1_TYPE { get; set; }
        public byte[] C_Value1_RTRef { get; set; }
        public byte[] C_Value1_RRRef { get; set; }
        public Nullable<decimal> C_Fld10871 { get; set; }
        public Nullable<decimal> C_TurnoverDt10881 { get; set; }
        public Nullable<decimal> C_TurnoverCt10882 { get; set; }
        public Nullable<decimal> C_Turnover10883 { get; set; }
        public Nullable<decimal> C_Fld10872 { get; set; }
        public Nullable<decimal> C_TurnoverDt10884 { get; set; }
        public Nullable<decimal> C_TurnoverCt10885 { get; set; }
        public Nullable<decimal> C_Turnover10886 { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
