//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgAT2415
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountRRef { get; set; }
        public byte[] C_Fld394RRef { get; set; }
        public byte[] C_Fld395RRef { get; set; }
        public byte[] C_Fld396RRef { get; set; }
        public byte[] C_Value1_TYPE { get; set; }
        public byte[] C_Value1_RTRef { get; set; }
        public byte[] C_Value1_RRRef { get; set; }
        public byte[] C_Value2_TYPE { get; set; }
        public byte[] C_Value2_RTRef { get; set; }
        public byte[] C_Value2_RRRef { get; set; }
        public Nullable<decimal> C_Fld397 { get; set; }
        public Nullable<decimal> C_TurnoverDt408 { get; set; }
        public Nullable<decimal> C_TurnoverCt409 { get; set; }
        public Nullable<decimal> C_Turnover410 { get; set; }
        public Nullable<decimal> C_Fld398 { get; set; }
        public Nullable<decimal> C_TurnoverDt411 { get; set; }
        public Nullable<decimal> C_TurnoverCt412 { get; set; }
        public Nullable<decimal> C_Turnover413 { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
