//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccChngR10867
    {
        public byte[] C_NodeTRef { get; set; }
        public byte[] C_NodeRRef { get; set; }
        public Nullable<decimal> C_MessageNo { get; set; }
        public byte[] C_IDRRef { get; set; }
    }
}
