//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Acc10
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public string C_OrderField { get; set; }
        public decimal C_Kind { get; set; }
        public byte[] C_OffBalance { get; set; }
        public byte[] C_Fld10860 { get; set; }
        public byte[] C_Fld11339RRef { get; set; }
        public byte[] C_Fld10861 { get; set; }
        public byte[] C_Fld10862 { get; set; }
    }
}
