//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgOpt
    {
        public byte[] C_RegID { get; set; }
        public System.DateTime C_Period { get; set; }
        public byte[] C_ActualPeriod { get; set; }
        public decimal C_Periodicity { get; set; }
        public decimal C_RepetitionFactor { get; set; }
        public decimal C_UseTotals { get; set; }
        public System.DateTime C_MinPeriod { get; set; }
        public byte[] C_UseSplitter { get; set; }
    }
}
