//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRg10893
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_AccountDtRRef { get; set; }
        public byte[] C_AccountCtRRef { get; set; }
        public byte[] C_Fld10894RRef { get; set; }
        public byte[] C_Fld10895DtRRef { get; set; }
        public byte[] C_Fld10895CtRRef { get; set; }
        public byte[] C_Fld11343DtRRef { get; set; }
        public byte[] C_Fld11343CtRRef { get; set; }
        public decimal C_Fld10896 { get; set; }
        public Nullable<decimal> C_Fld10897Dt { get; set; }
        public Nullable<decimal> C_Fld10897Ct { get; set; }
        public Nullable<decimal> C_Fld10898Dt { get; set; }
        public Nullable<decimal> C_Fld10898Ct { get; set; }
        public string C_Fld10899 { get; set; }
        public string C_Fld10900 { get; set; }
        public byte[] C_Fld10901 { get; set; }
        public byte[] C_Fld10902RRef { get; set; }
    }
}
