//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRgTn10472
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_Fld10452_TYPE { get; set; }
        public byte[] C_Fld10452_RTRef { get; set; }
        public byte[] C_Fld10452_RRRef { get; set; }
        public byte[] C_Fld10453RRef { get; set; }
        public byte[] C_Fld10454_TYPE { get; set; }
        public byte[] C_Fld10454_RTRef { get; set; }
        public byte[] C_Fld10454_RRRef { get; set; }
        public byte[] C_Fld10455RRef { get; set; }
        public byte[] C_Fld10456_TYPE { get; set; }
        public byte[] C_Fld10456_RTRef { get; set; }
        public byte[] C_Fld10456_RRRef { get; set; }
        public byte[] C_Fld10457_TYPE { get; set; }
        public byte[] C_Fld10457_RTRef { get; set; }
        public byte[] C_Fld10457_RRRef { get; set; }
        public byte[] C_Fld10458RRef { get; set; }
        public byte[] C_Fld10459RRef { get; set; }
        public byte[] C_Fld10460RRef { get; set; }
        public decimal C_Fld10461 { get; set; }
        public decimal C_Fld10462 { get; set; }
        public decimal C_Fld10463 { get; set; }
        public decimal C_Fld10464 { get; set; }
        public decimal C_Fld10465 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
