//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRg6500
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public decimal C_RecordKind { get; set; }
        public byte[] C_Fld6501RRef { get; set; }
        public byte[] C_Fld6502_TYPE { get; set; }
        public byte[] C_Fld6502_RTRef { get; set; }
        public byte[] C_Fld6502_RRRef { get; set; }
        public byte[] C_Fld6503RRef { get; set; }
        public byte[] C_Fld6504RRef { get; set; }
        public decimal C_Fld6505 { get; set; }
        public decimal C_Fld6506 { get; set; }
    }
}
