//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgCT10890
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountDtRRef { get; set; }
        public byte[] C_AccountCtRRef { get; set; }
        public byte[] C_Fld10869RRef { get; set; }
        public byte[] C_Fld10870DtRRef { get; set; }
        public byte[] C_Fld10870CtRRef { get; set; }
        public byte[] C_Fld11340DtRRef { get; set; }
        public byte[] C_Fld11340CtRRef { get; set; }
        public Nullable<decimal> C_Fld10871 { get; set; }
        public Nullable<decimal> C_Fld10872Dt { get; set; }
        public Nullable<decimal> C_Fld10872Ct { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
