//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgED10891
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public decimal C_Correspond { get; set; }
        public byte[] C_KindRRef { get; set; }
        public byte[] C_Value_TYPE { get; set; }
        public byte[] C_Value_RTRef { get; set; }
        public byte[] C_Value_RRRef { get; set; }
    }
}
