//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgAT110916
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountRRef { get; set; }
        public byte[] C_Fld10894RRef { get; set; }
        public byte[] C_Fld10895RRef { get; set; }
        public byte[] C_Fld11343RRef { get; set; }
        public byte[] C_Value1_TYPE { get; set; }
        public byte[] C_Value1_RTRef { get; set; }
        public byte[] C_Value1_RRRef { get; set; }
        public Nullable<decimal> C_Fld10896 { get; set; }
        public Nullable<decimal> C_TurnoverDt10907 { get; set; }
        public Nullable<decimal> C_TurnoverCt10908 { get; set; }
        public Nullable<decimal> C_Turnover10909 { get; set; }
        public Nullable<decimal> C_Fld10897 { get; set; }
        public Nullable<decimal> C_TurnoverDt10910 { get; set; }
        public Nullable<decimal> C_TurnoverCt10911 { get; set; }
        public Nullable<decimal> C_Turnover10912 { get; set; }
        public Nullable<decimal> C_Fld10898 { get; set; }
        public Nullable<decimal> C_TurnoverDt10913 { get; set; }
        public Nullable<decimal> C_TurnoverCt10914 { get; set; }
        public Nullable<decimal> C_Turnover10915 { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
