//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgOpt
    {
        public byte[] C_RegID { get; set; }
        public System.DateTime C_Period { get; set; }
        public byte[] C_ActualPeriod { get; set; }
        public decimal C_Periodicity { get; set; }
        public decimal C_RepetitionFactor { get; set; }
        public decimal C_UseTotals { get; set; }
        public System.DateTime C_MinPeriod { get; set; }
        public byte[] C_UseSplitter { get; set; }
    }
}
