//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRg6753
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_Fld6754RRef { get; set; }
        public byte[] C_Fld6755RRef { get; set; }
        public byte[] C_Fld6756RRef { get; set; }
        public byte[] C_Fld6757RRef { get; set; }
        public byte[] C_Fld6758RRef { get; set; }
        public byte[] C_Fld6759RRef { get; set; }
        public byte[] C_Fld6760RRef { get; set; }
        public byte[] C_Fld6761_TYPE { get; set; }
        public byte[] C_Fld6761_RTRef { get; set; }
        public byte[] C_Fld6761_RRRef { get; set; }
        public byte[] C_Fld6762RRef { get; set; }
        public byte[] C_Fld6763RRef { get; set; }
        public decimal C_Fld6764 { get; set; }
        public decimal C_Fld6765 { get; set; }
        public decimal C_Fld6766 { get; set; }
        public string C_Fld6767 { get; set; }
        public System.DateTime C_Fld6768 { get; set; }
        public string C_Fld6769 { get; set; }
    }
}
