//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgAT010906
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountRRef { get; set; }
        public byte[] C_Fld10894RRef { get; set; }
        public byte[] C_Fld10895RRef { get; set; }
        public byte[] C_Fld11343RRef { get; set; }
        public Nullable<decimal> C_Fld10896 { get; set; }
        public Nullable<decimal> C_TurnoverDt10907 { get; set; }
        public Nullable<decimal> C_TurnoverCt10908 { get; set; }
        public Nullable<decimal> C_Turnover10909 { get; set; }
        public Nullable<decimal> C_Fld10897 { get; set; }
        public Nullable<decimal> C_TurnoverDt10910 { get; set; }
        public Nullable<decimal> C_TurnoverCt10911 { get; set; }
        public Nullable<decimal> C_Turnover10912 { get; set; }
        public Nullable<decimal> C_Fld10898 { get; set; }
        public Nullable<decimal> C_TurnoverDt10913 { get; set; }
        public Nullable<decimal> C_TurnoverCt10914 { get; set; }
        public Nullable<decimal> C_Turnover10915 { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
