//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRgTn10122
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_Fld10107_TYPE { get; set; }
        public byte[] C_Fld10107_RTRef { get; set; }
        public byte[] C_Fld10107_RRRef { get; set; }
        public byte[] C_Fld10108RRef { get; set; }
        public byte[] C_Fld10109RRef { get; set; }
        public byte[] C_Fld10110_TYPE { get; set; }
        public byte[] C_Fld10110_RTRef { get; set; }
        public byte[] C_Fld10110_RRRef { get; set; }
        public byte[] C_Fld10111RRef { get; set; }
        public byte[] C_Fld10112_TYPE { get; set; }
        public byte[] C_Fld10112_RTRef { get; set; }
        public byte[] C_Fld10112_RRRef { get; set; }
        public byte[] C_Fld10113_TYPE { get; set; }
        public byte[] C_Fld10113_RTRef { get; set; }
        public byte[] C_Fld10113_RRRef { get; set; }
        public byte[] C_Fld10114RRef { get; set; }
        public byte[] C_Fld10115RRef { get; set; }
        public byte[] C_Fld10116RRef { get; set; }
        public decimal C_Fld10117 { get; set; }
        public decimal C_Fld10118 { get; set; }
        public decimal C_Fld10119 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
