//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgAT010880
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_AccountRRef { get; set; }
        public byte[] C_Fld10869RRef { get; set; }
        public byte[] C_Fld10870RRef { get; set; }
        public byte[] C_Fld11340RRef { get; set; }
        public Nullable<decimal> C_Fld10871 { get; set; }
        public Nullable<decimal> C_TurnoverDt10881 { get; set; }
        public Nullable<decimal> C_TurnoverCt10882 { get; set; }
        public Nullable<decimal> C_Turnover10883 { get; set; }
        public Nullable<decimal> C_Fld10872 { get; set; }
        public Nullable<decimal> C_TurnoverDt10884 { get; set; }
        public Nullable<decimal> C_TurnoverCt10885 { get; set; }
        public Nullable<decimal> C_Turnover10886 { get; set; }
        public decimal C_Splitter { get; set; }
    }
}
