//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRg10327
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public decimal C_RecordKind { get; set; }
        public byte[] C_Fld10328RRef { get; set; }
        public byte[] C_Fld10329RRef { get; set; }
        public byte[] C_Fld10330RRef { get; set; }
        public byte[] C_Fld10331RRef { get; set; }
        public byte[] C_Fld10332_TYPE { get; set; }
        public byte[] C_Fld10332_RTRef { get; set; }
        public byte[] C_Fld10332_RRRef { get; set; }
        public byte[] C_Fld10333RRef { get; set; }
        public byte[] C_Fld10334RRef { get; set; }
        public byte[] C_Fld10335RRef { get; set; }
        public decimal C_Fld10336 { get; set; }
        public decimal C_Fld10337 { get; set; }
        public byte[] C_Fld10338RRef { get; set; }
        public byte[] C_Fld10339 { get; set; }
        public decimal C_Fld10340 { get; set; }
        public byte[] C_Fld10341_TYPE { get; set; }
        public byte[] C_Fld10341_RTRef { get; set; }
        public byte[] C_Fld10341_RRRef { get; set; }
        public System.DateTime C_Fld10342 { get; set; }
        public decimal C_Fld10343 { get; set; }
    }
}
