//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Acc9_ExtDim10857
    {
        public byte[] C_Acc9_IDRRef { get; set; }
        public byte[] C_KeyField { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_DimKindRRef { get; set; }
        public byte[] C_DimIsMetadata { get; set; }
        public byte[] C_TurnoverOnly { get; set; }
        public byte[] C_Fld10858 { get; set; }
        public byte[] C_Fld11338 { get; set; }
    }
}
