//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRg6661
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_Fld6662_TYPE { get; set; }
        public byte[] C_Fld6662_RTRef { get; set; }
        public byte[] C_Fld6662_RRRef { get; set; }
        public byte[] C_Fld6663RRef { get; set; }
        public byte[] C_Fld6664RRef { get; set; }
        public byte[] C_Fld6665_TYPE { get; set; }
        public byte[] C_Fld6665_RTRef { get; set; }
        public byte[] C_Fld6665_RRRef { get; set; }
        public byte[] C_Fld6666RRef { get; set; }
        public byte[] C_Fld6667_TYPE { get; set; }
        public byte[] C_Fld6667_RTRef { get; set; }
        public byte[] C_Fld6667_RRRef { get; set; }
        public byte[] C_Fld6668_TYPE { get; set; }
        public byte[] C_Fld6668_RTRef { get; set; }
        public byte[] C_Fld6668_RRRef { get; set; }
        public byte[] C_Fld6669RRef { get; set; }
        public byte[] C_Fld6670RRef { get; set; }
        public byte[] C_Fld6671RRef { get; set; }
        public decimal C_Fld6672 { get; set; }
        public decimal C_Fld6673 { get; set; }
        public decimal C_Fld6674 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
