//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRgTn10006
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_Fld9988RRef { get; set; }
        public byte[] C_Fld9989RRef { get; set; }
        public byte[] C_Fld9990_TYPE { get; set; }
        public byte[] C_Fld9990_RTRef { get; set; }
        public byte[] C_Fld9990_RRRef { get; set; }
        public byte[] C_Fld9991RRef { get; set; }
        public byte[] C_Fld9992_TYPE { get; set; }
        public byte[] C_Fld9992_RTRef { get; set; }
        public byte[] C_Fld9992_RRRef { get; set; }
        public byte[] C_Fld9993_TYPE { get; set; }
        public byte[] C_Fld9993_RTRef { get; set; }
        public byte[] C_Fld9993_RRRef { get; set; }
        public byte[] C_Fld9994RRef { get; set; }
        public byte[] C_Fld9995_TYPE { get; set; }
        public byte[] C_Fld9995_RTRef { get; set; }
        public byte[] C_Fld9995_RRRef { get; set; }
        public byte[] C_Fld9996_TYPE { get; set; }
        public byte[] C_Fld9996_RTRef { get; set; }
        public byte[] C_Fld9996_RRRef { get; set; }
        public byte[] C_Fld9997_TYPE { get; set; }
        public byte[] C_Fld9997_RTRef { get; set; }
        public byte[] C_Fld9997_RRRef { get; set; }
        public byte[] C_Fld9998RRef { get; set; }
        public byte[] C_Fld9999_TYPE { get; set; }
        public byte[] C_Fld9999_RTRef { get; set; }
        public byte[] C_Fld9999_RRRef { get; set; }
        public decimal C_Fld10000 { get; set; }
        public decimal C_Fld10001 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
