//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRgED10891
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public decimal C_Correspond { get; set; }
        public byte[] C_KindRRef { get; set; }
        public byte[] C_Value_TYPE { get; set; }
        public byte[] C_Value_RTRef { get; set; }
        public byte[] C_Value_RRRef { get; set; }
    }
}
