//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRg10868
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_AccountDtRRef { get; set; }
        public byte[] C_AccountCtRRef { get; set; }
        public byte[] C_Fld10869RRef { get; set; }
        public byte[] C_Fld10870DtRRef { get; set; }
        public byte[] C_Fld10870CtRRef { get; set; }
        public byte[] C_Fld11340DtRRef { get; set; }
        public byte[] C_Fld11340CtRRef { get; set; }
        public decimal C_Fld10871 { get; set; }
        public Nullable<decimal> C_Fld10872Dt { get; set; }
        public Nullable<decimal> C_Fld10872Ct { get; set; }
        public string C_Fld10873 { get; set; }
        public string C_Fld10874 { get; set; }
        public byte[] C_Fld10875 { get; set; }
        public byte[] C_Fld10876RRef { get; set; }
    }
}
