//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRg420
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_AccountDtRRef { get; set; }
        public byte[] C_AccountCtRRef { get; set; }
        public byte[] C_Fld421RRef { get; set; }
        public byte[] C_Fld422DtRRef { get; set; }
        public byte[] C_Fld422CtRRef { get; set; }
        public byte[] C_Fld423DtRRef { get; set; }
        public byte[] C_Fld423CtRRef { get; set; }
        public decimal C_Fld424 { get; set; }
        public Nullable<decimal> C_Fld425Dt { get; set; }
        public Nullable<decimal> C_Fld425Ct { get; set; }
        public Nullable<decimal> C_Fld426Dt { get; set; }
        public Nullable<decimal> C_Fld426Ct { get; set; }
        public string C_Fld427 { get; set; }
        public string C_Fld428 { get; set; }
        public byte[] C_Fld429RRef { get; set; }
    }
}
