//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccRg393
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_AccountDtRRef { get; set; }
        public byte[] C_AccountCtRRef { get; set; }
        public byte[] C_Fld394RRef { get; set; }
        public byte[] C_Fld395DtRRef { get; set; }
        public byte[] C_Fld395CtRRef { get; set; }
        public byte[] C_Fld396DtRRef { get; set; }
        public byte[] C_Fld396CtRRef { get; set; }
        public decimal C_Fld397 { get; set; }
        public Nullable<decimal> C_Fld398Dt { get; set; }
        public Nullable<decimal> C_Fld398Ct { get; set; }
        public string C_Fld399 { get; set; }
        public string C_Fld400 { get; set; }
        public byte[] C_Fld401RRef { get; set; }
    }
}
