//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AccumRg6542
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_RecorderTRef { get; set; }
        public byte[] C_RecorderRRef { get; set; }
        public decimal C_LineNo { get; set; }
        public byte[] C_Active { get; set; }
        public byte[] C_Fld6543RRef { get; set; }
        public byte[] C_Fld6544RRef { get; set; }
        public byte[] C_Fld6545_TYPE { get; set; }
        public byte[] C_Fld6545_RTRef { get; set; }
        public byte[] C_Fld6545_RRRef { get; set; }
        public byte[] C_Fld6546RRef { get; set; }
        public byte[] C_Fld6547_TYPE { get; set; }
        public byte[] C_Fld6547_RTRef { get; set; }
        public byte[] C_Fld6547_RRRef { get; set; }
        public byte[] C_Fld6548_TYPE { get; set; }
        public byte[] C_Fld6548_RTRef { get; set; }
        public byte[] C_Fld6548_RRRef { get; set; }
        public byte[] C_Fld6549RRef { get; set; }
        public byte[] C_Fld6550_TYPE { get; set; }
        public byte[] C_Fld6550_RTRef { get; set; }
        public byte[] C_Fld6550_RRRef { get; set; }
        public byte[] C_Fld6551_TYPE { get; set; }
        public byte[] C_Fld6551_RTRef { get; set; }
        public byte[] C_Fld6551_RRRef { get; set; }
        public byte[] C_Fld6552_TYPE { get; set; }
        public byte[] C_Fld6552_RTRef { get; set; }
        public byte[] C_Fld6552_RRRef { get; set; }
        public byte[] C_Fld6553RRef { get; set; }
        public byte[] C_Fld6554_TYPE { get; set; }
        public byte[] C_Fld6554_RTRef { get; set; }
        public byte[] C_Fld6554_RRRef { get; set; }
        public decimal C_Fld6555 { get; set; }
        public decimal C_Fld6556 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
