//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference114
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public byte[] C_Fld1337 { get; set; }
        public byte[] C_Fld1338RRef { get; set; }
        public byte[] C_Fld1339RRef { get; set; }
        public byte[] C_Fld1340RRef { get; set; }
    }
}
