//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference56
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public byte[] C_Fld743RRef { get; set; }
        public Nullable<System.DateTime> C_Fld744 { get; set; }
        public string C_Fld745 { get; set; }
        public string C_Fld746 { get; set; }
        public byte[] C_Fld747 { get; set; }
        public string C_Fld748 { get; set; }
        public string C_Fld749 { get; set; }
        public string C_Fld750 { get; set; }
        public string C_Fld751 { get; set; }
        public string C_Fld752 { get; set; }
        public string C_Fld753 { get; set; }
        public byte[] C_Fld754RRef { get; set; }
        public byte[] C_Fld755RRef { get; set; }
        public byte[] C_Fld756RRef { get; set; }
        public string C_Fld757 { get; set; }
        public string C_Fld758 { get; set; }
        public string C_Fld759 { get; set; }
        public byte[] C_Fld760RRef { get; set; }
        public byte[] C_Fld761RRef { get; set; }
        public byte[] C_Fld762RRef { get; set; }
        public byte[] C_Fld763 { get; set; }
        public byte[] C_Fld764 { get; set; }
    }
}
