//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference63
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public string C_Fld937 { get; set; }
        public byte[] C_Fld938RRef { get; set; }
        public byte[] C_Fld939RRef { get; set; }
        public byte[] C_Fld940RRef { get; set; }
        public string C_Fld941 { get; set; }
        public string C_Fld942 { get; set; }
        public byte[] C_Fld943RRef { get; set; }
        public byte[] C_Fld944RRef { get; set; }
        public byte[] C_Fld945 { get; set; }
        public byte[] C_Fld946RRef { get; set; }
        public string C_Fld947 { get; set; }
        public Nullable<decimal> C_Fld948 { get; set; }
        public byte[] C_Fld949RRef { get; set; }
        public string C_Fld950 { get; set; }
    }
}
