//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference23
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_OwnerID_TYPE { get; set; }
        public byte[] C_OwnerID_RTRef { get; set; }
        public byte[] C_OwnerID_RRRef { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public byte[] C_Fld497RRef { get; set; }
        public byte[] C_Fld498RRef { get; set; }
        public byte[] C_Fld499RRef { get; set; }
        public string C_Fld500 { get; set; }
        public Nullable<System.DateTime> C_Fld501 { get; set; }
        public Nullable<System.DateTime> C_Fld502 { get; set; }
        public byte[] C_Fld503RRef { get; set; }
        public byte[] C_Fld504 { get; set; }
        public string C_Fld505 { get; set; }
        public byte[] C_Fld506RRef { get; set; }
        public string C_Fld507 { get; set; }
        public byte[] C_Fld508 { get; set; }
        public string C_Fld509 { get; set; }
        public string C_Fld510 { get; set; }
        public byte[] C_Fld511RRef { get; set; }
        public byte[] C_Fld512RRef { get; set; }
        public Nullable<decimal> C_Fld513 { get; set; }
        public byte[] C_Fld514RRef { get; set; }
        public byte[] C_Fld515_TYPE { get; set; }
        public string C_Fld515_S { get; set; }
        public byte[] C_Fld515_RTRef { get; set; }
        public byte[] C_Fld515_RRRef { get; set; }
        public byte[] C_Fld516_TYPE { get; set; }
        public string C_Fld516_S { get; set; }
        public byte[] C_Fld516_RTRef { get; set; }
        public byte[] C_Fld516_RRRef { get; set; }
        public byte[] C_Fld517_TYPE { get; set; }
        public string C_Fld517_S { get; set; }
        public byte[] C_Fld517_RTRef { get; set; }
        public byte[] C_Fld517_RRRef { get; set; }
        public byte[] C_Fld518RRef { get; set; }
    }
}
