//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference69
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public string C_Fld943 { get; set; }
        public byte[] C_Fld944RRef { get; set; }
        public byte[] C_Fld945 { get; set; }
        public Nullable<decimal> C_Fld946 { get; set; }
        public byte[] C_Fld947 { get; set; }
        public byte[] C_Fld948 { get; set; }
        public byte[] C_Fld949 { get; set; }
        public byte[] C_Fld950 { get; set; }
        public byte[] C_Fld951RRef { get; set; }
        public byte[] C_Fld952RRef { get; set; }
        public string C_Fld953 { get; set; }
        public string C_Fld954 { get; set; }
        public byte[] C_Fld955RRef { get; set; }
        public byte[] C_Fld956RRef { get; set; }
        public byte[] C_Fld957RRef { get; set; }
        public string C_Fld958 { get; set; }
        public byte[] C_Fld959RRef { get; set; }
        public byte[] C_Fld960 { get; set; }
        public byte[] C_Fld961RRef { get; set; }
        public byte[] C_Fld962 { get; set; }
        public byte[] C_Fld963 { get; set; }
        public byte[] C_Fld964RRef { get; set; }
        public byte[] C_Fld965RRef { get; set; }
        public byte[] C_Fld966RRef { get; set; }
        public byte[] C_Fld967RRef { get; set; }
        public byte[] C_Fld968RRef { get; set; }
        public byte[] C_Fld969RRef { get; set; }
        public string C_Fld970 { get; set; }
        public Nullable<decimal> C_Fld971 { get; set; }
        public byte[] C_Fld972RRef { get; set; }
        public byte[] C_Fld973RRef { get; set; }
        public byte[] C_Fld974RRef { get; set; }
        public byte[] C_Fld975RRef { get; set; }
        public byte[] C_Fld976RRef { get; set; }
        public string C_Fld977 { get; set; }
        public byte[] C_Fld978 { get; set; }
    }
}
