//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference62
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public byte[] C_Fld708RRef { get; set; }
        public byte[] C_Fld709RRef { get; set; }
        public Nullable<System.DateTime> C_Fld710 { get; set; }
        public string C_Fld711 { get; set; }
        public string C_Fld712 { get; set; }
        public string C_Fld713 { get; set; }
        public byte[] C_Fld714RRef { get; set; }
        public byte[] C_Fld715 { get; set; }
        public string C_Fld716 { get; set; }
        public string C_Fld717 { get; set; }
        public string C_Fld718 { get; set; }
        public string C_Fld719 { get; set; }
        public string C_Fld720 { get; set; }
        public string C_Fld721 { get; set; }
        public byte[] C_Fld722RRef { get; set; }
        public byte[] C_Fld723RRef { get; set; }
        public byte[] C_Fld724RRef { get; set; }
        public byte[] C_Fld725 { get; set; }
        public byte[] C_Fld726 { get; set; }
        public string C_Fld727 { get; set; }
        public byte[] C_Fld728RRef { get; set; }
        public byte[] C_Fld729RRef { get; set; }
        public byte[] C_Fld730RRef { get; set; }
        public string C_Fld731 { get; set; }
        public Nullable<decimal> C_Fld732 { get; set; }
        public string C_Fld733 { get; set; }
        public string C_Fld734 { get; set; }
        public byte[] C_Fld735RRef { get; set; }
        public byte[] C_Fld736RRef { get; set; }
        public byte[] C_Fld737RRef { get; set; }
        public byte[] C_Fld738RRef { get; set; }
        public byte[] C_Fld739 { get; set; }
        public byte[] C_Fld740 { get; set; }
    }
}
