//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference67
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public byte[] C_Fld829RRef { get; set; }
        public byte[] C_Fld830RRef { get; set; }
        public Nullable<System.DateTime> C_Fld831 { get; set; }
        public string C_Fld832 { get; set; }
        public string C_Fld833 { get; set; }
        public string C_Fld834 { get; set; }
        public byte[] C_Fld835RRef { get; set; }
        public byte[] C_Fld836 { get; set; }
        public string C_Fld837 { get; set; }
        public string C_Fld838 { get; set; }
        public string C_Fld839 { get; set; }
        public string C_Fld840 { get; set; }
        public string C_Fld841 { get; set; }
        public string C_Fld842 { get; set; }
        public byte[] C_Fld843RRef { get; set; }
        public byte[] C_Fld844RRef { get; set; }
        public byte[] C_Fld845RRef { get; set; }
        public byte[] C_Fld846 { get; set; }
        public byte[] C_Fld847 { get; set; }
        public string C_Fld848 { get; set; }
        public byte[] C_Fld849RRef { get; set; }
        public byte[] C_Fld850RRef { get; set; }
        public byte[] C_Fld851RRef { get; set; }
        public string C_Fld852 { get; set; }
        public Nullable<decimal> C_Fld853 { get; set; }
        public string C_Fld854 { get; set; }
        public string C_Fld855 { get; set; }
        public byte[] C_Fld856RRef { get; set; }
        public byte[] C_Fld857RRef { get; set; }
        public byte[] C_Fld858RRef { get; set; }
        public byte[] C_Fld859RRef { get; set; }
        public byte[] C_Fld860 { get; set; }
    }
}
