//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Reference77
    {
        public byte[] C_IDRRef { get; set; }
        public byte[] C_Version { get; set; }
        public byte[] C_Marked { get; set; }
        public byte[] C_IsMetadata { get; set; }
        public byte[] C_ParentIDRRef { get; set; }
        public byte[] C_Folder { get; set; }
        public string C_Code { get; set; }
        public string C_Description { get; set; }
        public string C_Fld1073 { get; set; }
        public byte[] C_Fld1074RRef { get; set; }
        public byte[] C_Fld1075 { get; set; }
        public Nullable<decimal> C_Fld1076 { get; set; }
        public byte[] C_Fld1077 { get; set; }
        public byte[] C_Fld1078 { get; set; }
        public byte[] C_Fld1079 { get; set; }
        public byte[] C_Fld1080 { get; set; }
        public byte[] C_Fld1081RRef { get; set; }
        public byte[] C_Fld1082RRef { get; set; }
        public string C_Fld1083 { get; set; }
        public string C_Fld1084 { get; set; }
        public byte[] C_Fld1085RRef { get; set; }
        public byte[] C_Fld1086RRef { get; set; }
        public byte[] C_Fld1087RRef { get; set; }
        public string C_Fld1088 { get; set; }
        public byte[] C_Fld1089RRef { get; set; }
        public byte[] C_Fld1090 { get; set; }
        public byte[] C_Fld1091RRef { get; set; }
        public byte[] C_Fld1092 { get; set; }
        public byte[] C_Fld1093 { get; set; }
        public byte[] C_Fld1094RRef { get; set; }
        public byte[] C_Fld1095RRef { get; set; }
        public byte[] C_Fld1096RRef { get; set; }
        public byte[] C_Fld1097RRef { get; set; }
        public byte[] C_Fld1098RRef { get; set; }
        public string C_Fld1099 { get; set; }
        public Nullable<decimal> C_Fld1100 { get; set; }
        public byte[] C_Fld1101RRef { get; set; }
        public byte[] C_Fld1102RRef { get; set; }
        public byte[] C_Fld1103RRef { get; set; }
        public byte[] C_Fld1104RRef { get; set; }
        public string C_Fld1105 { get; set; }
    }
}
