//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SeqB10834
    {
        public byte[] C_Fld10833RRef { get; set; }
        public System.DateTime C_Period { get; set; }
        public byte[] C_Recorder_TYPE { get; set; }
        public byte[] C_Recorder_RTRef { get; set; }
        public byte[] C_Recorder_RRRef { get; set; }
    }
}
