//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SeqB10831
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_Recorder_TYPE { get; set; }
        public byte[] C_Recorder_RTRef { get; set; }
        public byte[] C_Recorder_RRRef { get; set; }
    }
}
