//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base2Entities : DbContext
    {
        public base2Entities()
            : base("name=base2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Reference91> C_Reference91 { get; set; }
        public virtual DbSet<C_AccumRg6542> C_AccumRg6542 { get; set; }
        public virtual DbSet<C_Reference62> C_Reference62 { get; set; }
        public virtual DbSet<C_AccumRgTn6677> C_AccumRgTn6677 { get; set; }
        public virtual DbSet<C_AccumRgTn6903> C_AccumRgTn6903 { get; set; }
        public virtual DbSet<C_Reference69> C_Reference69 { get; set; }
        public virtual DbSet<C_AccumRg6500> C_AccumRg6500 { get; set; }
        public virtual DbSet<C_Reference23> C_Reference23 { get; set; }
        public virtual DbSet<C_AccumRg6661> C_AccumRg6661 { get; set; }
        public virtual DbSet<C_AccumRg6753> C_AccumRg6753 { get; set; }
    }
}
