//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Acc10> C_Acc10 { get; set; }
        public DbSet<C_Acc9> C_Acc9 { get; set; }
        public DbSet<C_Acc9_ExtDim10857> C_Acc9_ExtDim10857 { get; set; }
        public DbSet<C_AccChngR10859> C_AccChngR10859 { get; set; }
        public DbSet<C_AccChngR10867> C_AccChngR10867 { get; set; }
        public DbSet<C_AccRg10868> C_AccRg10868 { get; set; }
        public DbSet<C_AccRg10893> C_AccRg10893 { get; set; }
        public DbSet<C_AccRgAT010880> C_AccRgAT010880 { get; set; }
        public DbSet<C_AccRgAT010906> C_AccRgAT010906 { get; set; }
        public DbSet<C_AccRgAT110887> C_AccRgAT110887 { get; set; }
        public DbSet<C_AccRgAT110916> C_AccRgAT110916 { get; set; }
        public DbSet<C_AccRgAT210888> C_AccRgAT210888 { get; set; }
        public DbSet<C_AccRgAT210917> C_AccRgAT210917 { get; set; }
        public DbSet<C_AccRgAT310889> C_AccRgAT310889 { get; set; }
        public DbSet<C_AccRgAT310918> C_AccRgAT310918 { get; set; }
        public DbSet<C_AccRgChngR10892> C_AccRgChngR10892 { get; set; }
        public DbSet<C_AccRgChngR10921> C_AccRgChngR10921 { get; set; }
        public DbSet<C_AccRgCT10890> C_AccRgCT10890 { get; set; }
        public DbSet<C_AccRgCT10919> C_AccRgCT10919 { get; set; }
        public DbSet<C_AccRgED10891> C_AccRgED10891 { get; set; }
        public DbSet<C_AccRgED10920> C_AccRgED10920 { get; set; }
        public DbSet<C_AccRgOpt> C_AccRgOpt { get; set; }
        public DbSet<C_Seq10830> C_Seq10830 { get; set; }
        public DbSet<C_Seq10832> C_Seq10832 { get; set; }
        public DbSet<C_SeqB10831> C_SeqB10831 { get; set; }
        public DbSet<C_SeqB10834> C_SeqB10834 { get; set; }
        public DbSet<C_YearOffset> C_YearOffset { get; set; }
        public DbSet<C_Reference114> C_Reference114 { get; set; }
    }
}
