//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressoExpert.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RgTn2
    {
        public System.DateTime C_Period { get; set; }
        public byte[] C_Fld6883_TYPE { get; set; }
        public byte[] C_Fld6883_RTRef { get; set; }
        public byte[] C_Fld6883_RRRef { get; set; }
        public byte[] C_Fld6884RRef { get; set; }
        public byte[] C_Fld6885_TYPE { get; set; }
        public byte[] C_Fld6885_RTRef { get; set; }
        public byte[] C_Fld6885_RRRef { get; set; }
        public byte[] C_Fld6886RRef { get; set; }
        public byte[] C_Fld6887_TYPE { get; set; }
        public byte[] C_Fld6887_RTRef { get; set; }
        public byte[] C_Fld6887_RRRef { get; set; }
        public byte[] C_Fld6888_TYPE { get; set; }
        public byte[] C_Fld6888_RTRef { get; set; }
        public byte[] C_Fld6888_RRRef { get; set; }
        public byte[] C_Fld6889RRef { get; set; }
        public byte[] C_Fld6890RRef { get; set; }
        public byte[] C_Fld6891RRef { get; set; }
        public decimal C_Fld6892 { get; set; }
        public decimal C_Fld6893 { get; set; }
        public decimal C_Fld6894 { get; set; }
        public decimal C_Fld6895 { get; set; }
        public decimal C_Fld6896 { get; set; }
        public decimal C_DimHash { get; set; }
    }
}
